
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",

  # package moves client-go 4.0 to 5.0
  "k8s.io/api/core/v1",
  "k8s.io/api/admissionregistration/v1alpha1",
  "k8s.io/api/apps/v1beta1",
  "k8s.io/api/authentication/v1",
  "k8s.io/api/authentication/v1beta1",
  "k8s.io/api/authorization/v1",
  "k8s.io/api/authorization/v1beta1",
  "k8s.io/api/autoscaling/v1",
  "k8s.io/api/autoscaling/v2beta1",
  "k8s.io/api/batch/v1",
  "k8s.io/api/batch/v2alpha1",
  "k8s.io/api/certificates/v1beta1",
  "k8s.io/api/extensions/v1beta1",
  "k8s.io/api/networking/v1",
  "k8s.io/api/policy/v1beta1",
  "k8s.io/api/rbac/v1alpha1",
  "k8s.io/api/rbac/v1beta1",
  "k8s.io/api/settings/v1alpha1",
  "k8s.io/api/storage/v1",
  "k8s.io/api/storage/v1beta1",
  "k8s.io/client-go/kubernetes/typed/autoscaling/v2beta1",
]

ignored = [
  "k8s.io/client-go/pkg/api",
  "k8s.io/client-go/pkg/api/v1",
  "k8s.io/client-go/pkg/apis/admissionregistration/v1alpha1",
  "k8s.io/client-go/pkg/apis/apps/v1beta1",
  "k8s.io/client-go/pkg/apis/authentication/v1",
  "k8s.io/client-go/pkg/apis/authentication/v1beta1",
  "k8s.io/client-go/pkg/apis/authorization/v1",
  "k8s.io/client-go/pkg/apis/authorization/v1beta1",
  "k8s.io/client-go/pkg/apis/autoscaling/v1",
  "k8s.io/client-go/pkg/apis/autoscaling/v2alpha1",
  "k8s.io/client-go/pkg/apis/batch/v1",
  "k8s.io/client-go/pkg/apis/batch/v2alpha1",
  "k8s.io/client-go/pkg/apis/certificates/v1beta1",
  "k8s.io/client-go/pkg/apis/extensions/v1beta1",
  "k8s.io/client-go/pkg/apis/networking/v1",
  "k8s.io/client-go/pkg/apis/policy/v1beta1",
  "k8s.io/client-go/pkg/apis/rbac/v1alpha1",
  "k8s.io/client-go/pkg/apis/rbac/v1beta1",
  "k8s.io/client-go/pkg/apis/settings/v1alpha1",
  "k8s.io/client-go/pkg/apis/storage/v1",
  "k8s.io/client-go/pkg/apis/storage/v1beta1",
  "k8s.io/client-go/kubernetes/typed/autoscaling/v2alpha1",
]


[[constraint]]
  name = "cloud.google.com/go"
  version = "0.11.0"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "~10.2.1-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "~8.1.x"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.26"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/robfig/cron"
  revision = "df38d32658d8788cd446ba74db4bb5375c4b0cb3"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/satori/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/afero"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "019ae5ada31de202164b118aee88ee2d14075c31"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~5.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "~1.8"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "93622da34e54fb6529bfb7c57e710f37a8d9cbd8"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.8"
  name = "k8s.io/code-generator"

[[override]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"
